[package]
name = "example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "example"

[[bin]]
name = "example"
path = "src/lib.rs"

[dependencies]
tessera = { path = "../tessera" }
tessera_macros = { path = "../tessera_macros" }
tessera_basic_components = { path = "../tessera_basic_components" }
rand = "0.9.1"
tokio = { version = "1.45.1", features = ["full"] }
log = "0.4.20"
parking_lot = "0.12.1"
winit = "0.30.11"
wgpu = "25.0.2"
env_logger = "0.11.8"
pollster = "0.4.0"
bytemuck = { version = "1.12", features = ["derive"] }
image = "0.25.6"

[target.'cfg(not(target_os = "android"))'.dependencies]
flexi_logger = { version = "0.31.1", features = ["async"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15.0"
