[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
tessera = { path = "../tessera" }
tessera_macros = { path = "../tessera_macros" }
tessera_basic_components = { path = "../tessera_basic_components" }

[profile.release]
debug = true
lto = true
