[package]
name = "example"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]
name = "example"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
tessera-ui = { path = "../tessera-ui" }
tessera-ui-macros = { path = "../tessera-ui-macros" }
tessera-ui-basic-components = { path = "../tessera-ui-basic-components" }
rand = "0.9.2"
tokio = { version = "1.45.1", features = ["full"] }
log = "0.4.27"
parking_lot = "0.12.4"
winit = "0.30.12"
wgpu = "26.0.1"
env_logger = "0.11.8"
pollster = "0.4.0"
bytemuck = { version = "1.23.1", features = ["derive"] }
image = "0.25.6"

[target.'cfg(not(target_os = "android"))'.dependencies]
flexi_logger = { version = "0.31.2", features = ["async", "trc"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15.1"
