[package]
name = "tessera"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.0"
env_logger = "0.11.8"
log = "0.4.27"
parking_lot = "0.12.3"
tokio = { version = "1.45.0", features = ["full"] }
wgpu = "25.0.0"
glyphon = "0.9.0"
winit = "0.30.11"
earcutr = "0.4.3"
