[lib]
proc-macro = true

[package]
name = "tessera-ui-macros"
version = "0.1.7"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Macros of tessera-ui, for creating functional components."
readme = "README.md"

[features]
default = ["shard"]
shard = []

[dependencies]
heck = "0.5.0"
quote = "1.0.40"
syn = "2.0.101"
