[lib]
proc-macro = true

[package]
name = "tessera-ui-macros"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
quote = "1.0.40"
syn = "2.0.101"
tessera-ui = { path = "../tessera-ui" }
