[package]
name = "tessera_basic_components"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = "0.20.2"
glyphon = "0.9.0"
parking_lot = "0.12.4"
tessera = { path = "../tessera" }
tessera_macros = { path = "../tessera_macros" }
