name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Check all targets
        run: cargo check --all-targets --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install rust-script
        run: cargo install rust-script
      - name: Check formatting
        run: cargo fmt --all -- --check && rust-script scripts/check-imports.rs .

  check_android:
    name: Check Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          targets: aarch64-linux-android
      - uses: Swatinem/rust-cache@v2
      - name: Install xbuild
        run: cargo install xbuild
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c
      - name: Check Android target
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: x build  --platform android --arch arm64 -p example
